### PR TITLE
Picklist edit #164

### LINKED ISSUE #164: [ Enhancement ] - Edit picklist field
We can add custom type to the generic datatable,

here the idea is to allow edition of picklist field 

I found an existing approach : https://upsource.solutions/blog/69-adding-a-picklist-to-the-lightning-datatable.html

### PR DESCRIPTION
**Pull request by mickaelgudin**
# Description

- **extendedDatatable :** component that extends lightning:datatable with a new custom data type (picklist)
- **RelatedList.ColumnJson :** add typeAttributes to construct options of picklist on edit
- **datatablePicklistColumn :** a new component that is used as the template for picklist columns

Fixes #164 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] edit only one picklist value for one row (StageName of Opportunity)
- [x] edit several rows and several columns(including a picklist column : StageName of Opportunity)
- [x] edit several rows and sort

# Tests

- I made few changes in existing apex classes and added a unit test method in order to keep the coverage close to 90%

### CODE REVIEW

**Comment by Sarveshgithub** [comment]
@mickaelgudin thanks for your contribution,
- Can this be not achieved without a child component (extendedDatatable , datatablePicklistColumn ) because I want to be a keep single component, let me know if this really needs a child camp.
- Please remove console.log() statements

For testing: 
- direct provide picklist field API with comma separated? is any other value that needs to give?
- have you tested FLS as well? i guess it should work, for read-only edits should disable

**Comment by mickaelgudin** [comment]
@Sarveshgithub 

- Yes we need others components that's the way to go
- Ok I'll remove the console.log() statements

for testing :

- We only show active picklist values, I didn't let the users the possibility to have values not defined in the picklist values
- I haven't tested FLS

**Comment by Sarveshgithub** [comment]
@mickaelgudin ok sounds good, let me know once log are removed

**Comment by mickaelgudin** [comment]
@Sarveshgithub I removed the console.log statements

**Comment by Sarveshgithub** [comment]
hi @mickaelgudin, i have tested this change, getting an error, 'Unscripted error' in Org, and this is not working in local dev ( localhost ). getting below error:
Steps to reproduce : 
1. Start local dev server
2. configLocal(this, true); // set this to true
3. Open lwcRelated component
image

**Comment by Sarveshgithub** [comment]
@mickaelgudin Yes, I have deployed it's failing in org as well, but it should work in local dev as well, no sure why it's failing

**Comment by mickaelgudin** [comment]
@Sarveshgithub are you deploying using git, or through xml package?

**Comment by Sarveshgithub** [comment]
@mickaelgudin deploying via VS code directly from 'dev' branch

**Comment by mickaelgudin** [comment]
@Sarveshgithub alright I will look into it, 
I'll keep you posted

**Comment by Sarveshgithub** [comment]
@mickaelgudin I have analzed, 
`import LightningDatatable from 'lightning/datatable';` this is not supported in localhost dev.
In org working fine. all good

**Pull request merged**
