### PR TITLE
fixes #5 :  optional icon  + autoretrieve of the icon name based on s…

### LINKED ISSUE #5: Icon name based on SObject
This new feature would : 
- retrieve the icon name based on the SObject api name (making the icon name optional)
- allow to override the default icon(still letting the user define the icon and only using the default icon if none is specified)

It's seems easy to implement based on this post : https://developer.salesforce.com/forums/?id=9062I000000IQ3eQAG

I will do a PR soon.

### PR DESCRIPTION
**Pull request by mickaelgudin**
…object name

### CODE REVIEW

**Comment by Sarveshgithub** [comment]
Nice Idea make Icon dynamically,
@mickaelgudin I do have a question, can this icon information can't get from 'lightning/uiObjectInfoApi' property. I mean I am trying to avoid Apex calls. : [Example ](https://salesforce.stackexchange.com/questions/268249/soql-query-or-other-means-to-get-the-icon-assigned-to-an-object.)
and to get dynamic sobject Information: Here is the [example ](https://salesforce.stackexchange.com/questions/314479/can-we-use-a-variable-to-pass-to-the-lightning-uiobjectinfoapi-to-enable-dynamic). see if this is possible.

**Comment by mickaelgudin** [comment]
@Sarveshgithub  I chose this solution because : 
-  'lightning/uiObjectInfoApi' returns not the icon url and not the name .
-   I don't want to use  tag to display the icon (using the url)
-  If we try to get the icon name from the url it could be error prone

The solution is based on this thread : https://developer.salesforce.com/forums/?id=9062I000000IQ3eQAG
from the last post to be precise, where the situation is similar : 
the person wants the icon name and not the url and states 'I tried the below and was able to get it dynamically for standard and Custom objects.' after someone shared the first solution which was based on 'lightning/uiObjectInfoApi'.

As for the performance issues : 
There is still a single call (retrieves records + icon name at once).
But I could still enhance the performance / logic separation of the solution :
- In the apex controller RelatedList the the call to getIconName should be called if the icon name is empty
- Move the getIconName to another apex class (IconUtils) but still called from RelatedList apex class (separating logic)

Let me know what you think about this remarks and suggestions.

**Comment by Sarveshgithub** [comment]
@mickaelgudin  yhea fair points, definitely last two suggestions can reduce some server call depending on icon value. can you please make those changes? after that, I will merge these changes.

**Comment by mickaelgudin** [comment]
@Sarveshgithub yes I will implement the suggested changes

**Pull request merged**
